In [4]:
#SciPy-Scientific Python
import scipy
from scipy import constants
print(scipy.__version__)#checking scipy version

1.7.3


# constants

In [7]:
#CONSTANT UNITS, list of all units are seen using dir()
from scipy import constants
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [10]:
# Return the specified  unit in meter
print(constants.yotta)    #1e+24
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.peta)     #1000000000000000.0
print(constants.tera)     #1000000000000.0
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0
print(constants.deka)     #10.0
print(constants.deci)     #0.1
print(constants.centi)    #0.01
print(constants.milli)    #0.001
print(constants.micro)    #1e-06
print(constants.nano)     #1e-09
print(constants.pico)     #1e-12
print(constants.femto)    #1e-15
print(constants.atto)     #1e-18
print(constants.zepto)    #1e-21
   

1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [11]:
print(constants.nano)

1e-09


In [19]:
# PREFIXES, returns unit in bytes
from scipy import constants
#Binary
print(constants.kibi)  
#Mass, returns in kg
print(constants.gram)
print(constants.pound)
#Angle, returns in radian
print(constants.degree)
#Time, returns unit in seconds
print(constants.minute)
print(constants.day)
#length, retuns in meters
print(constants.inch)
print(constants.mile)
#Pressure, returns in pascals
print(constants.atmosphere)

1024
0.001
0.45359236999999997
0.017453292519943295
60.0
86400.0
0.0254
1609.3439999999998
101325.0


# Scipy optimizers

In [26]:
#optimizers, set of procedures  defined in SciPy
        
#find root of an equation; x + cos(x)

#x is the actual solution
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn, 0)
print(myroot.x)




[-0.73908513]


In [27]:
#print all information about the solution
print(myroot)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [30]:

#MINIMIZING A FUNCTION
#finding minima
import scipy
from scipy.optimize import minimize
def eqn (x):
    return x **2 + x +2
mymin = minimize(eqn, 0, method = "BFGS")
mymin


      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])

# SciPy Sparse Data

In [31]:
#Sparse module that provides functions to deal with sparse data


<module 'scipy.sparse' from 'C:\\Users\\PC\\anaconda3\\lib\\site-packages\\scipy\\sparse\\__init__.py'>


In [32]:
#CSC-Compressed Sparse Column
#CSR -Compressed Sparse Row

#Q. Create a CSR matrix from an array
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])
print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


3 items have value:
    row 0, position 5-value 1/
    row 0, position 6 -value 1/
    row 0, postion 8 -value2

In [34]:
arr = np.array([1, 2, 3, 4, 5, 0, 0, 0, ])
print(csr_matrix(arr))

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (0, 3)	4
  (0, 4)	5


(row, columns)

In [37]:
#SPARSE MATRIX Methods, viewing stored data with data()property
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array ([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(arr)
print(csr_matrix(arr))#returns items with data with zero ites
print(csr_matrix(arr).data)#returns stored data without zero item

[[0 0 0]
 [0 0 1]
 [1 0 2]]
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2
[1 1 2]


In [38]:
# count_nonzero() method:Counting nonzeros 
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(csr_matrix(arr).count_nonzero()) 

3


In [41]:
#eliminate_zeros(); removing zero entries from the matrix
print(arr)
mat  = csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

[[0 0 0]
 [0 0 1]
 [1 0 2]]
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [44]:
#sum_duplicates() ; eliminating duplicates
print(arr)
mat = csr_matrix(arr)
mat.sum_duplicates()
print(mat)

[[0 0 0]
 [0 0 1]
 [1 0 2]]
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [45]:
#tocsc(), Converting from csr to csc 
newarr = csr_matrix(arr).tocsc()
print(newarr)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2
